In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array(['a', 'b'])

array(['a', 'b'], dtype='<U1')

In [4]:
np.array(['a', 1, True])

array(['a', '1', 'True'], dtype='<U21')

array cannot have elements with different type, when you try it it will be convert to most general type (in that case -> str)

In [5]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [6]:
x[2]

3

In [7]:
x[1:3]

array([2, 3])

In [8]:
x[:3]

array([1, 2, 3])

In [9]:
x[[2,0,3]]

array([3, 1, 4])

In [10]:
x[[True, False, False, True]]

array([1, 4])

In [11]:
x[1:3] = [20, 30]
x

array([ 1, 20, 30,  4])

when you want use it numer of elements for both side should be equal, except when you want change all elements to the same value

In [12]:
x[1:3] = 100
x

array([  1, 100, 100,   4])

FUNKCJE AGREGUJĄCE

In [13]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [14]:
len(x)

4

In [15]:
np.sum(x)

10

In [16]:
sum(x)

10

In [17]:
np.max(x)

4

In [18]:
np.min(x)

1

In [19]:
np.mean(x) #średnia

2.5

In [20]:
np.std(x) #odchylenie standardowe

1.118033988749895

In [21]:
y = np.array([True, False, False, False, False, False])
y

array([ True, False, False, False, False, False])

In [22]:
np.any(y) # sprawdza czy chociaż jeden z elementów jest prawdziwy

True

In [23]:
np.all(y) # sprawdza czy wszystkie są prawdziwe

False

In [24]:
# Średnia na dwa sposoby:
print(np.mean(x))


2.5


In [25]:
print(x)

[1 2 3 4]


In [26]:
x.mean()

2.5

# Operacje zwektoryzowane

In [27]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 10, 20, 30, 40])

In [28]:
x + y

array([ 0, 11, 22, 33, 44])

In [29]:
x + 100

array([100, 101, 102, 103, 104])

In [30]:
x + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [ ]:
x - y

In [31]:
np.abs(x - y)

array([ 0,  9, 18, 27, 36])

In [32]:
np.mean(np.abs(x - y))

18.0

In [33]:
(x - y)**2

array([   0,   81,  324,  729, 1296])

In [34]:
np.sum((x - y)**2)

2430

In [35]:
np.sqrt(np.abs(x - y))

array([0.        , 3.        , 4.24264069, 5.19615242, 6.        ])

In [36]:
np.power(x, 3)

array([ 0,  1,  8, 27, 64])

In [37]:
np.power(x, y)

array([              1,               1,         1048576, 205891132094649,
                     0])

In [38]:
x > y

array([False, False, False, False, False])

In [39]:
x > 2

array([False, False, False,  True,  True])

In [40]:
z = x[x > 2]
z

array([3, 4])

In [41]:
sum_elements_more_than_2 = np.sum(x[x > 2])
sum_elements_more_than_2

7

In [42]:
(x > 1) & (x < 3)

array([False, False,  True, False, False])

In [43]:
x[(x > 1) & (x < 3)]

array([2])

In [44]:
x > 2

array([False, False, False,  True,  True])

In [45]:
np.sum(x > 2)

2

In [46]:
len(x[x > 2])

2

In [47]:
x.shape

(5,)

# Macierze

In [48]:
x = np.array(
    [[1, 2, 3, 4],
    [5, 6, 7 ,8],
    [9, 10, 11, 12]]
)

In [49]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
x.shape

(3, 4)

In [51]:
x[1, 2]

7

In [52]:
x[1:3, 0:2]

array([[ 5,  6],
       [ 9, 10]])

In [53]:
x[2, :]

array([ 9, 10, 11, 12])

In [54]:
x[2]

array([ 9, 10, 11, 12])

In [55]:
x[:, 3]

array([ 4,  8, 12])

In [56]:
x.min()

1

In [58]:
np.min(x)

1

In [65]:
# srednia po kolumnach
x.mean(0)

array([5., 6., 7., 8.])

In [66]:
# średnia po wierszach
x.mean(1)

array([ 2.5,  6.5, 10.5])

In [67]:
x + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [69]:
y = x * 10
y

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [70]:
x + y

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132]])

In [76]:
a = np.array([1, 2, 3, 4])

In [77]:
a

array([1, 2, 3, 4])

In [78]:
x + a
# tzw. mechanizm broadcasting'u, rozszerzenie kształtu

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [81]:
b = np.array([
    [100],
    [200],
    [300]
]
)
b

array([[100],
       [200],
       [300]])

In [82]:
b.shape

(3, 1)

In [83]:
a.shape

(4,)

In [84]:
x + b

array([[101, 102, 103, 104],
       [205, 206, 207, 208],
       [309, 310, 311, 312]])

In [85]:
x + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [89]:
# max w każdej kolumnie
max_in_col = x.max(0)
max_in_col

array([ 9, 10, 11, 12])

In [90]:
x/max_in_col

array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [0.55555556, 0.6       , 0.63636364, 0.66666667],
       [1.        , 1.        , 1.        , 1.        ]])

In [91]:
# odjęcie średniej o z każdej kolumny
x - x.mean(0)

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [93]:
# Matematyczne mnożenie macierzy (nie element po elemencie)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
A.shape

(2, 3)

In [97]:
B.shape

(3, 2)

In [98]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [99]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [100]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
A.shape

(2, 3)

In [102]:
A.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
A.reshape((6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [106]:
# jak nie znamy ilości elementów dokładnie to można tak
A.reshape((6, -1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [107]:
A.reshape((5, -1))

ValueError: cannot reshape array of size 6 into shape (5,newaxis)

In [108]:
A.reshape((3, -1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
# zamiana macierzy na tab jednowymiarową
A.reshape(-1)

array([1, 2, 3, 4, 5, 6])

# Użyteczne funkcjonalności

In [112]:
np.zeros(3)

array([0., 0., 0.])

In [113]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [114]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [118]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [119]:
np.ones_like(a)

array([1, 1, 1])

In [125]:
# tworzy tablice od 0 - pierwszy argument włącznie, do 50 - drugi argument bez tej wartości, z krokiem 5 - trzeci argument
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [127]:
# tworzy tablica od 0 - pierwszy argument włącznie, do 4 - drugi argument włącznie,
# o długości/ilości elementów 4 - trzeci argument, wartości są równoodległe od siebie
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [129]:
# losowe wartości od 0 - pierwszy argument, do 3 - drugi argument, w ilości 5 - trzeci argument, z rozkładu normalnego
# każda wartość równie prawdopodobna
np.random.uniform(0, 3, 5)

array([1.06882163, 1.68982774, 2.77022603, 1.20386036, 1.43616701])

In [134]:
x = np.array([0, -1, 2, -3, 4, -5, 6, -7, 8, -9])
x

array([ 0, -1,  2, -3,  4, -5,  6, -7,  8, -9])

In [135]:
np.argmax(x)

8

In [136]:
x.argmax()

8

In [137]:
np.argmin(x)

9

In [140]:
np.argmax(np.array([1, 2, 2, 3, 3, 3, 3]))

3

In [141]:
np.where(x > 5)

(array([6, 8]),)

In [142]:
np.where(x > 5)[0]

array([6, 8])

In [143]:
np.where(x > 5, 5, 0)

array([0, 0, 0, 0, 0, 0, 5, 0, 5, 0])

In [144]:
np.unique(x)

array([-9, -7, -5, -3, -1,  0,  2,  4,  6,  8])

In [145]:
np.unique(x, return_counts = True)

(array([-9, -7, -5, -3, -1,  0,  2,  4,  6,  8]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [147]:
np.sort(x)

array([-9, -7, -5, -3, -1,  0,  2,  4,  6,  8])

In [148]:
np.argsort(x)

array([9, 7, 5, 3, 1, 0, 2, 4, 6, 8])

In [150]:
x[np.argsort(x)]

array([-9, -7, -5, -3, -1,  0,  2,  4,  6,  8])

# Brak danych

In [152]:
x = np.array([1, 2, np.nan, 4, np.nan])
x

array([ 1.,  2., nan,  4., nan])

In [155]:
len(x)

5

In [157]:
np.isnan(x)

array([False, False,  True, False,  True])

In [158]:
np.sum(np.isnan(x))

2

In [159]:
np.sum(x)

nan

In [162]:
np.sum(x[~np.isnan(x)])

7.0

# Zadania
## Zadanie 1.3.1
 

Zaimportuj bibliotekę numpy (użyj aliasu np). Zdefiniuj dwie tablice:

x = np.arange(0, 60, 10)
y = np.array([7, 35, 22, 19, 40, 39])

a następnie:

* Oblicz na ilu pozycjach wartości w wektorze x są większe niż w wektorze y.
* Oblicz jaka jest średnia różnica między wartościami w wektorach x i y.
* Oblicz jaka jest średnia z wartości bezwzględnych różnic między wartościami w
wektorach x i y.

* Oblicz jaka jest średnia z wartość kwadratu różnic między wartościami w wektorach x i y.
* Oblicz na ilu pozycjach wektory x i y różnią się o więcej niż 10.
* Zwróć te wartości z tablicy x, których pierwiastek nie różni się o więcej niż 1 od pierwiastka z wartości w wektorze y, stojących na odpowiadających im pozycjach.
* Zwróć te elementy z wektora x, które od wartości najmniejszej w wektorze x nie różnią się o więcej niż 30.
* Zamień w wektorze x wartości większe niż średnia z wartości wektora x na wartość 10.
 

## Zadanie 1.3.2
 

* Często stosowanym zabiegiem podczas przygotowywania danych do nauki algorytmów uczenia maszynowego jest standaryzacja danych, która polega na tym, że w każdej kolumnie danej macierzy liczb od wszystkich wartości wartości w kolumnie odejmujemy średnią z kolumny i dzielimy te różnice przez odchylenie standardowe w danej kolumnie. Zaimplementuj standaryzację i dla przykładowej macierzy oblicz średnie i odchylenia standardowe w kolumnach po standaryzacji.
* Czasem również wykorzystywane jest przekształcenie polegające na tym, że dzielimy wartości w każdej kolumnie przez wartość największą w danej kolumnie. Zaimplementuj tę transformację i dla przykładowej macierzy o wartościach dodatnich, oblicz wartości maksymalne w kolumnach po takim przekształceniu macierzy.
* Innym użytecznym zabiegiem jest tzw. normalizacja wierszy, która może być realizowana w różnych wariantach. Zaimplementuj normalizację macierzy polegającą na tym, że każdy wiersz (wszystkie wartości w wierszu) dzielimy przez sumę wartości w danym wierszu oraz taką, która polega na tym, że wiersze dzielimy przez pierwiastek z sumy kwadratów wartości w danym wierszu (czyli przez tzw. normę euklidesową wektora).

In [164]:
# 1.3.1
x = np.arange(0, 60, 10)
y = np.array([7, 35, 22, 19, 40, 39])

In [165]:
x

array([ 0, 10, 20, 30, 40, 50])

In [166]:
y

array([ 7, 35, 22, 19, 40, 39])

In [167]:
np.sum(x > y)

2

In [170]:
np.mean(x - y)

-2.0

In [171]:
np.mean(np.abs(x - y))

9.333333333333334

In [172]:
np.mean((x - y)**2)

153.33333333333334

In [178]:
np.sum(np.abs(x - y) > 10)

3

In [176]:
(x - y)**2

array([ 49, 625,   4, 121,   0, 121])

In [180]:
x[np.abs(np.sqrt(x) - np.sqrt(y)) <= 1]

array([20, 40, 50])

In [182]:
x[(x - x.min()) <= 30]

array([ 0, 10, 20, 30])

In [183]:
np.where(x > x.mean(), 10, x) 

array([ 0, 10, 20, 10, 10, 10])

In [ ]:
# 1.3.2
