In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array(['a', 'b'])

array(['a', 'b'], dtype='<U1')

In [5]:
np.array(['a', 1, True])

array(['a', '1', 'True'], dtype='<U21')

array cannot have elements with different type, when you try it it will be convert to most general type (in that case -> str)

In [6]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [7]:
x[2]

3

In [8]:
x[1:3]

array([2, 3])

In [9]:
x[:3]

array([1, 2, 3])

In [10]:
x[[2,0,3]]

array([3, 1, 4])

In [11]:
x[[True, False, False, True]]

array([1, 4])

In [13]:
x[1:3] = [20, 30]
x

array([ 1, 20, 30,  4])

when you want use it numer of elements for both side should be equal, except when you want change all elements to the same value

In [14]:
x[1:3] = 100
x

array([  1, 100, 100,   4])